from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Optional
from vault.model import Connection, ConnKey, ConnectionGrant, ConnectionAccessLog, Token


class Store(ABC):
    @abstractmethod
    def put_connection(self, conn: Connection) -> None: ...
    @abstractmethod
    def get_connection(self, key: ConnKey) -> Optional[Connection]: ...
    @abstractmethod
    def list_connections(self, org: str, provider: Optional[str]) -> list[Connection]: ...
    @abstractmethod
    def write_token(self, key: ConnKey, token: Token, now: float) -> None: ...
    @abstractmethod
    def acquire_lease(self, key: ConnKey, holder: str, until: float, now: float) -> bool: ...
    @abstractmethod
    def release_lease(self, key: ConnKey, holder: str) -> None: ...
    @abstractmethod
    def lease_held(self, key: ConnKey, now: float) -> bool: ...
    @abstractmethod
    def delete_connection(self, key: ConnKey) -> None: ...
    @abstractmethod
    def add_grant(self, grant: ConnectionGrant) -> None: ...
    @abstractmethod
    def get_grants(self, connection_id: str) -> list[ConnectionGrant]: ...
    @abstractmethod
    def append_log(self, entry: ConnectionAccessLog) -> None: ...
    @abstractmethod
    def read_log(self, connection_id: str) -> list[ConnectionAccessLog]: ...
