from abc import ABC, abstractmethod
from typing import Optional
from identity.model import (
    Principal, Org, Membership, Grant, McpToken, OAuthClient,
    OAuthAuthCode, OAuthAccessToken, AccessLog, IslandRegistry,
)


class IdentityStore(ABC):
    @abstractmethod
    def put_principal(self, p: Principal) -> None: ...
    @abstractmethod
    def get_principal(self, principal_id: str) -> Optional[Principal]: ...
    @abstractmethod
    def get_principal_by_email(self, email: str) -> Optional[Principal]: ...

    @abstractmethod
    def put_org(self, o: Org) -> None: ...
    @abstractmethod
    def get_org(self, org_id: str) -> Optional[Org]: ...

    @abstractmethod
    def put_membership(self, m: Membership) -> None: ...
    @abstractmethod
    def get_membership(self, principal_id: str, org_id: str) -> Optional[Membership]: ...
    @abstractmethod
    def list_memberships(self, principal_id: str) -> list[Membership]: ...

    @abstractmethod
    def add_grant(self, g: Grant) -> None: ...
    @abstractmethod
    def revoke_grant(self, grant_id: str, at: float) -> None: ...
    @abstractmethod
    def list_grants(self, principal_id: str) -> list[Grant]: ...

    @abstractmethod
    def put_mcp_token(self, t: McpToken) -> None: ...
    @abstractmethod
    def get_mcp_token(self, token_hash: str) -> Optional[McpToken]: ...

    @abstractmethod
    def put_oauth_client(self, c: OAuthClient) -> None: ...
    @abstractmethod
    def get_oauth_client(self, client_id: str) -> Optional[OAuthClient]: ...

    @abstractmethod
    def put_auth_code(self, c: OAuthAuthCode) -> None: ...
    @abstractmethod
    def get_auth_code(self, code_hash: str) -> Optional[OAuthAuthCode]: ...
    @abstractmethod
    def consume_auth_code(self, code_hash: str, at: float) -> bool: ...

    @abstractmethod
    def put_access_token(self, t: OAuthAccessToken) -> None: ...
    @abstractmethod
    def get_access_token(self, token_hash: str) -> Optional[OAuthAccessToken]: ...
    @abstractmethod
    def rotate_refresh(self, old_hash: str, new_token: OAuthAccessToken) -> None: ...

    @abstractmethod
    def access_token_hashes(self) -> list[str]: ...

    @abstractmethod
    def append_log(self, entry: AccessLog) -> None: ...
    @abstractmethod
    def read_log(self, principal_id: str) -> list[AccessLog]: ...

    @abstractmethod
    def put_island(self, i: IslandRegistry) -> None: ...
    @abstractmethod
    def get_island(self, island_id: str) -> Optional[IslandRegistry]: ...
    @abstractmethod
    def get_island_by_audience(self, audience: str) -> Optional[IslandRegistry]: ...
    @abstractmethod
    def list_islands(self) -> list[IslandRegistry]: ...
    @abstractmethod
    def disable_island(self, island_id: str, at: float) -> None: ...
